// Copyright (C) 2024 owoDra

#pragma once

#include "NativeGameplayTags.h"


////////////////////////////////////
// DataBase.Weapon...Dagger

BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_AttackRadius_Dagger_Normal_First);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_AttackRadius_Dagger_Normal_Second);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_AttackRadius_Dagger_Normal_Third);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_AttackRadius_Dagger_Normal_Four);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_AttackRadius_Dagger_Normal_Five);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_AttackRadius_Dagger_Special_Second);

BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_AttackDistance_Dagger_Normal_First);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_AttackDistance_Dagger_Normal_Second);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_AttackDistance_Dagger_Normal_Third);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_AttackDistance_Dagger_Normal_Four);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_AttackDistance_Dagger_Normal_Five);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_AttackDistance_Dagger_Special_Second);

BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_AttackSpeed_Dagger_Normal_First);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_AttackSpeed_Dagger_Normal_Second);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_AttackSpeed_Dagger_Normal_Third);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_AttackSpeed_Dagger_Normal_Four);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_AttackSpeed_Dagger_Normal_Five);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_AttackSpeed_Dagger_Special_Second);

BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_AttackDamage_Dagger_Normal_First);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_AttackDamage_Dagger_Normal_Second);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_AttackDamage_Dagger_Normal_Third);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_AttackDamage_Dagger_Normal_Four);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_AttackDamage_Dagger_Normal_Five);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_AttackDamage_Dagger_Special_Second);

BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_HeadMultiply_Dagger_Normal_First);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_HeadMultiply_Dagger_Normal_Second);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_HeadMultiply_Dagger_Normal_Third);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_HeadMultiply_Dagger_Normal_Four);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_HeadMultiply_Dagger_Normal_Five);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_HeadMultiply_Dagger_Special_Second);

BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_Misc_Dagger_Special_First_MoveDuration);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_Misc_Dagger_Special_First_MoveStrength);
