// Copyright (C) 2024 owoDra

#pragma once

#include "NativeGameplayTags.h"


////////////////////////////////////
// DataBase.Weapon.Katana

BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_Katana_Normal_First_Size);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_Katana_Normal_First_Speed);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_Katana_Normal_First_Damage);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_Katana_Normal_First_Distance);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_Katana_Normal_First_HeadMultiply);

BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_Katana_Normal_Second_Size);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_Katana_Normal_Second_Speed);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_Katana_Normal_Second_Damage);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_Katana_Normal_Second_Distance);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_Katana_Normal_Second_HeadMultiply);

BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_Katana_Normal_Third_Size);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_Katana_Normal_Third_Speed);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_Katana_Normal_Third_Damage);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_Katana_Normal_Third_Distance);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_Katana_Normal_Third_HeadMultiply);

BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_Katana_Charge_First_ChargeTime);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_Katana_Charge_First_MoveDuration);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_Katana_Charge_First_MoveStrength);

BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_Katana_Charge_Second_Size);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_Katana_Charge_Second_Speed);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_Katana_Charge_Second_Damage);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_Katana_Charge_Second_Distance);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_Katana_Charge_Second_HeadMultiply);
