// Copyright (C) 2024 owoDra

#pragma once

#include "NativeGameplayTags.h"


////////////////////////////////////
// DataBase.Weapon...Katana

BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_AttackRadius_Katana_Normal_First);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_AttackRadius_Katana_Normal_Second);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_AttackRadius_Katana_Normal_Third);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_AttackRadius_Katana_Charge_Second);

BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_AttackDistance_Katana_Normal_First);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_AttackDistance_Katana_Normal_Second);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_AttackDistance_Katana_Normal_Third);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_AttackDistance_Katana_Charge_Second);

BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_AttackSpeed_Katana_Normal_First);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_AttackSpeed_Katana_Normal_Second);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_AttackSpeed_Katana_Normal_Third);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_AttackSpeed_Katana_Charge_Second);

BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_AttackDamage_Katana_Normal_First);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_AttackDamage_Katana_Normal_Second);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_AttackDamage_Katana_Normal_Third);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_AttackDamage_Katana_Charge_Second);

BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_HeadMultiply_Katana_Normal_First);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_HeadMultiply_Katana_Normal_Second);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_HeadMultiply_Katana_Normal_Third);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_HeadMultiply_Katana_Charge_Second);

BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_Misc_Katana_Charge_First_ChargeTime);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_Misc_Katana_Charge_First_MoveDuration);
BEDATABASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DataBase_Weapon_Misc_Katana_Charge_First_MoveStrength);
